import { injectable } from 'inversify'
import { ApplicationStatus, DatacapAllocator } from '@src/domain/application/application'

@injectable()
export class MessageService {
  generatePullRequestMessage(application: DatacapAllocator): string {
    const submissionDate = new Date().toISOString().split('T')[0]
    const githubLink = `https://github.com/${application.applicantGithubHandle}`

    const message = `
# Filecoin Plus Allocator Application

## Application Details
| Field | Value |
|-------|-------|
| Number | \`${application.applicationNumber}\` |
| Applicant | ${application.applicantName} |
| Organization | ${application.applicantOrgName} |
| Address | [${application.applicantAddress}](https://filfox.info/en/address/${encodeURIComponent(application.applicantAddress)}) |
| GitHub Username | [![GitHub](https://img.shields.io/badge/GitHub-${
      application.applicantGithubHandle
    }?style=flat-square&logo=github)](${githubLink}) |
| Location | ${application.applicantLocation} |

---
<sup>This message was automatically generated by the Filecoin Plus Bot. For more information, visit [filecoin.io](https://filecoin.io)</sup>
`

    return message.trim()
  }

  generateCommentMessage(application: DatacapAllocator): string {
    const statusEmoji = {
      [ApplicationStatus.SUBMISSION_PHASE]: '📝',
      [ApplicationStatus.KYC_PHASE]: '🔍',
      [ApplicationStatus.GOVERNANCE_REVIEW_PHASE]: '👥',
      [ApplicationStatus.RKH_APPROVAL_PHASE]: '🔑',
      [ApplicationStatus.APPROVED]: '✅',
      [ApplicationStatus.REJECTED]: '❌',
    }

    let message = `
## Application Status: \`${application.applicationStatus}\` ${statusEmoji[application.applicationStatus] || '❓'}

`

    message += this.getStatusSpecificMessage(application)

    message += `
---
<sup>This message was automatically generated by the Filecoin Plus Bot. For more information, visit [filecoin.io](https://filecoin.io)</sup>
`

    return message
  }

  private getStatusSpecificMessage(application: DatacapAllocator): string {
    switch (application.applicationStatus) {
      case ApplicationStatus.KYC_PHASE:
        return this.getKYCStatusMessage(application)
      case ApplicationStatus.GOVERNANCE_REVIEW_PHASE:
        return this.getGovernanceReviewStatusMessage(application)
      case ApplicationStatus.RKH_APPROVAL_PHASE:
        return this.getRKHApprovalStatusMessage(application)
      case ApplicationStatus.APPROVED:
        return this.getApprovedStatusMessage(application)
      case ApplicationStatus.REJECTED:
        return this.getRejectedStatusMessage(application)
      default:
        return `
### Need Assistance?
- For questions about the application process, please contact our support team

> 📞 We're here to help if you need any assistance
`
    }
  }

  private getKYCStatusMessage(application: DatacapAllocator): string {
    return `
### Next Steps
1. Complete the KYC process at [our secure portal](https://flow-dev.togggle.io/fidl/kyc?applicationId=${application.guid})
   - **Name:** ${application.applicantName}
   - **GitHub Username:** ${application.applicantGithubHandle}
2. Your application will be automatically updated once submitted

> ℹ️ KYC completion is required to proceed with your application
`
  }

  private getGovernanceReviewStatusMessage(application: DatacapAllocator): string {
    return `
### Discussion Phase
- Your application is currently under review by the Fil+ governance committee
- Discussion may be required to clarify certain aspects of your application

> 📝 Please be prepared to respond to any questions in this PR
`
  }

  private getRKHApprovalStatusMessage(application: DatacapAllocator): string {
    return `
### Approval Pending
- Your application is awaiting final approval from on-chain signers
- We'll update this thread once a decision has been made

> ⏳ The final decision is pending. Thank you for your patience.
`
  }

  private getApprovedStatusMessage(application: DatacapAllocator): string {
    return `
### Application Approved
- Congratulations! Your application to become a datacap allocator has been approved
- You will receive further instructions shortly

> 🎉 Welcome to the Filecoin Plus community!
`
  }

  private getRejectedStatusMessage(application: DatacapAllocator): string {
    return `
### Application Rejected
- We regret to inform you that your application has been rejected

> ❌ Please contact our support team for more information
`
  }
}
