"use client"; // TODO: Remove this with providers refactor

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { FilsnapProvider } from "@/providers/filsnap-provider";
import { Navbar } from "@/components/Navbar";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FilsnapProvider
          snapId="npm:filsnap"
          snapVersion=">=0.5.0"
          config={{
            network: "testnet",
          }}
        >
          
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster />
        </FilsnapProvider>
      </body>
    </html>
  );
}
