export const TYPES = {
  ApiServer: Symbol("ApiServer"),
  AirtableClient: Symbol("AirtableClient"),
  AirtableClientConfig: Symbol("AirtableClientConfig"),
  CommandBus: Symbol("CommandBus"),
  CommandHandler: Symbol("CommandHandler"),
  DatacapAllocatorEventStore: Symbol("DatacapAllocatorEventStore"),
  DatacapAllocatorRepository: Symbol("DatacapAllocatorRepository"),
  Db: Symbol("Db"),
  Event: Symbol("Event"),
  EventBus: Symbol("EventBus"),
  GithubClient: Symbol("GithubClient"),
  GithubClientConfig: Symbol("GithubClientConfig"),
  LotusClient: Symbol("LotusClient"),
  LotusClientConfig: Symbol("LotusClientConfig"),
  QueryBus: Symbol("QueryBus"),
  QueryHandler: Symbol("QueryHandler"),
  RabbitMQConfig: Symbol("RabbitMQConfig"),
};
